package api_test

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// specPath is the committed OpenAPI spec, regenerated by `make swagger`.
const specPath = "../server/docs/swagger.json"

// TestSwaggerShapes pins what the .swaggo override buys. The drift gate
// only proves the spec matches the annotations, so a dropped override
// plus a committed regen would be green while every descriptor, record
// and records array silently reverts to swag's []byte rendering
// ([]integer) and generated clients type them as number[].
func TestSwaggerShapes(t *testing.T) {
	raw, err := os.ReadFile(specPath)
	if err != nil {
		t.Fatalf("read spec: %v", err)
	}
	if n := strings.Count(string(raw), `"items": {"type": "integer"}`) +
		strings.Count(string(raw), `"items":{"type":"integer"}`); n != 0 {
		t.Errorf("spec has %d []integer schemas — is .swaggo still in place? run `make swagger`", n)
	}

	var spec struct {
		Components struct {
			Schemas map[string]struct {
				Properties map[string]json.RawMessage `json:"properties"`
			} `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(raw, &spec); err != nil {
		t.Fatalf("parse spec: %v", err)
	}

	// object: an arbitrary-keyed JSON object (descriptors, records).
	// bare: an object with no value schema — the per-path patch maps,
	// whose values are whatever the path takes.
	const object = `{"additionalProperties":{},"type":"object"}`
	const bare = `{"type":"object"}`
	for _, tc := range []struct{ schema, field, want string }{
		{"api.AddPropertyRequest", "xFormat", object},
		{"api.PropertyDef", "xFormat", object},
		{"api.DatasetFieldDraft", "xFormat", object},
		{"api.PartDraftRequest", "ui", object},
		{"api.PartDefResponse", "ui", object},
		{"api.TypeInfo", "layout", object},
		{"api.ObjectGetResponse", "record", object},
		{"api.DatasetSchema", "schema", object},
		{"api.PropertyPatchRequest", "set", bare},
		{"api.PartPatchRequest", "set", bare},
		{"api.BlockPatchRequest", "set", bare},
	} {
		got, ok := spec.Components.Schemas[tc.schema].Properties[tc.field]
		if !ok {
			t.Errorf("%s.%s: missing from the spec", tc.schema, tc.field)
			continue
		}
		if s := normalize(t, got); s != tc.want {
			t.Errorf("%s.%s = %s, want %s", tc.schema, tc.field, s, tc.want)
		}
	}

	// Record arrays are arrays OF objects, the shape a per-field
	// swaggertype cannot express (swag v2 rc5 segfaults on it).
	for _, schema := range []string{"api.QueryResponse", "api.AggregateResponse", "api.LocalAggregateResponse"} {
		got, ok := spec.Components.Schemas[schema].Properties["records"]
		if !ok {
			t.Errorf("%s.records: missing from the spec", schema)
			continue
		}
		var arr struct {
			Type  string          `json:"type"`
			Items json.RawMessage `json:"items"`
		}
		if err := json.Unmarshal(got, &arr); err != nil {
			t.Fatalf("%s.records: %v", schema, err)
		}
		if arr.Type != "array" || normalize(t, arr.Items) != object {
			t.Errorf("%s.records = %s, want an array of %s", schema, got, object)
		}
	}
}

// normalize drops the doc comment swag copies onto a field and
// re-marshals with sorted keys, so a schema compares as one string.
func normalize(t *testing.T, raw json.RawMessage) string {
	t.Helper()
	var m map[string]any
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("parse schema: %v", err)
	}
	delete(m, "description")
	out, err := json.Marshal(m)
	if err != nil {
		t.Fatalf("marshal schema: %v", err)
	}
	return string(out)
}
